server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/question_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  application:
    name: question-service
